'use client';

import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, BarChart3, Check, ChevronLeft, ChevronRight, CircleDollarSign, Database, FileSearch, HomeIcon, Info, ListFilter, RotateCcw, Scale, Search, ShieldAlert, ShieldCheck } from 'lucide-react';
import prototype from '@/data/prototype.json';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type Listing = (typeof prototype.listings)[number];
type Filter = 'material' | 'all' | 'include' | 'duplicate_collapsed' | 'needs_human_review' | 'exclude';
const money = (value: number) => `₹${new Intl.NumberFormat('en-IN').format(value)}`;
const stateLabel: Record<string, string> = { include: 'Included', exclude: 'Excluded', duplicate_collapsed: 'Collapsed', needs_human_review: 'Review pending' };

function StateBadge({ state }: { state: string }) {
  const tone = state === 'needs_human_review' ? 'border-amber-200 bg-amber-50 text-amber-900' : state === 'duplicate_collapsed' ? 'border-sky-200 bg-sky-50 text-sky-900' : state === 'include' ? 'border-indigo-200 bg-indigo-50 text-indigo-900' : 'border-border bg-muted/45 text-muted-foreground';
  return <Badge variant="outline" className={tone}>{stateLabel[state] ?? state}</Badge>;
}

export default function Home() {
  const [filter, setFilter] = useState<Filter>('material');
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Listing | null>(null);
  const [policyOpen, setPolicyOpen] = useState(false);
  const [runOpen, setRunOpen] = useState(false);
  const [whatIfId, setWhatIfId] = useState<string | null>(null);
  const [scenarioId, setScenarioId] = useState(prototype.economics.scenarios[0].id);
  const [resolvedQueue, setResolvedQueue] = useState<string[]>([]);
  const pageSize = 12;
  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return prototype.listings.filter((listing) => {
      const state = listing.decision.b2State;
      const matches = filter === 'all' || (filter === 'material' && state !== 'exclude') || state === filter;
      const haystack = [listing.listingId, listing.observed.source, listing.observed.society, ...listing.decision.reasonCodes].join(' ').toLowerCase();
      return matches && (!needle || haystack.includes(needle));
    });
  }, [filter, query]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const safePage = Math.min(page, totalPages);
  const visibleRows = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);
  const whatIf = prototype.marketEvidence.counterfactuals.find((item) => item.id === whatIfId);
  const scenario = prototype.economics.scenarios.find((item) => item.id === scenarioId) ?? prototype.economics.scenarios[0];
  const setActiveFilter = (value: Filter) => { setFilter(value); setPage(1); };

  return <main className="min-h-screen bg-background text-foreground">
    <div className="border-b border-amber-200 bg-amber-50 px-4 py-2 text-center text-xs font-semibold text-amber-950">Frozen exercise snapshot · evidence through 18 Aug 2026 · the packet&apos;s “sign this week” window has expired · not live or actionable</div>
    <header className="sticky top-0 z-30 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1600px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-sm"><ShieldCheck className="size-5" /></div><div><p className="text-[11px] font-bold tracking-[0.18em] text-primary">BOSS · FLENT</p><p className="text-sm font-semibold">Market Evidence Inspector</p></div></div><div className="flex items-center gap-2"><Badge variant="outline" className="hidden border-indigo-200 bg-indigo-50 text-indigo-900 sm:inline-flex">Candidate policy · v{prototype.snapshot.policyVersion}</Badge><Button variant="outline" size="sm" onClick={() => setRunOpen(true)}><Database /> <span className="hidden sm:inline">Run details</span></Button></div></div></header>
    <div className="mx-auto grid max-w-[1600px] grid-cols-1 lg:grid-cols-[216px_minmax(0,1fr)]">
      <aside className="hidden min-h-[calc(100vh-6.1rem)] border-r border-border/80 bg-sidebar px-4 py-6 lg:block"><Button variant="ghost" className="mb-6 w-full justify-start text-muted-foreground"><ArrowLeft /> All deals</Button><nav aria-label="Prototype sections" className="space-y-1">{[[HomeIcon,'Decision context','#decision-context'],[BarChart3,'Market evidence','#market-evidence'],[ListFilter,'Listing audit','#listing-audit'],[CircleDollarSign,'Economics context','#economics-context'],[FileSearch,'Resolution queue','#resolution-queue']].map(([Icon,label,href], index) => { const NavIcon = Icon as typeof HomeIcon; return <a key={label as string} href={href as string} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${index === 1 ? 'bg-sidebar-accent text-sidebar-accent-foreground' : 'text-muted-foreground hover:bg-sidebar-accent/60 hover:text-foreground'}`}><NavIcon className="size-4" />{label as string}</a>; })}</nav><div className="mt-8 rounded-xl border bg-card p-3.5"><p className="text-xs font-semibold">Packet reference</p><p className="mt-1.5 text-sm font-semibold text-amber-800">Provisional HOLD</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Supplied in boss-assessment.md. Not generated by Problem 1 or this prototype.</p></div></aside>
      <section className="min-w-0 px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1320px]">
        <div id="decision-context" className="mb-6 scroll-mt-28 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><span>{prototype.snapshot.caseId}</span><span>·</span><span>{prototype.case.subject.society}</span><span>·</span><span>2BHK · 1,175 sq ft · semi-furnished</span></div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Can the market benchmark be trusted enough to use?</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Inspect what the supplied marketplace evidence supports, why each row received its state, and where a responsible system must abstain.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setPolicyOpen(true)}><Scale /> View candidate policy</Button><Button render={<a href="#listing-audit" aria-label="Inspect all 86 listing rows" />}><ListFilter /> Inspect 86 rows <ChevronRight /></Button></div></div>
        <div id="market-evidence" className="scroll-mt-28 grid gap-4 xl:grid-cols-[1.45fr_0.8fr]">
          <Card><CardHeader><CardTitle>Evidence result</CardTitle><CardDescription>Retained asking-price evidence under the frozen candidate policy.</CardDescription><CardAction><Badge variant="outline" className="border-indigo-200 bg-indigo-50 text-indigo-900">Conditional stability · HIGH</Badge></CardAction></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-[1.05fr_1fr]"><div className="rounded-2xl border border-indigo-200 bg-indigo-50/65 p-5"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-700">B2 retained asking median</p><p className="mt-2 text-4xl font-bold tracking-tight text-indigo-950">{money(prototype.marketEvidence.baselines.B2.estimate)}</p><p className="mt-2 text-sm text-indigo-900/75">8 effective rows · 3 observed portal labels · 0.429% maximum leave-one-group-out movement</p></div><div className="space-y-3"><div className="rounded-xl border bg-muted/35 p-4"><p className="text-xs font-medium text-muted-foreground">Middle 50% of retained asking prices</p><p className="mt-1 text-xl font-bold">{money(prototype.marketEvidence.b2_observed_asking_rent_band.p25)}–{money(prototype.marketEvidence.b2_observed_asking_rent_band.p75)}</p><p className="mt-1 text-xs text-muted-foreground">Observed P25–P75 spread; not a confidence interval or achievable-rent range.</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-semibold text-amber-900">Translation to achievable base rent · LOW</p><p className="mt-1 text-xs leading-5 text-amber-950">Asking prices are not signed rents, and listing maintenance basis cannot be normalized.</p></div></div></div></CardContent></Card>
          <Card><CardHeader><CardTitle>What this result does not mean</CardTitle><CardDescription>Guardrails against automation bias.</CardDescription></CardHeader><CardContent className="space-y-3">{['HIGH is conditional sample stability—not probability of truth or deal confidence.','Three portal labels are not three independent sources.','The eight effective rows are not proven to be eight independent homes.','The prototype did not generate the packet’s HOLD decision.','₹58,250 cannot be cleanly compared with ₹56k base or ₹61k all-in.'].map((item) => <div key={item} className="flex gap-2.5 text-sm leading-5 text-muted-foreground"><Info className="mt-0.5 size-4 shrink-0 text-indigo-600" /><p>{item}</p></div>)}</CardContent></Card>
        </div>
        <Card className="mt-4"><CardHeader><CardTitle>Baseline and complexity challenge</CardTitle><CardDescription>B2 must earn its operational cost over a credible simple workflow.</CardDescription><CardAction><Badge variant="secondary">Six variants · ₹58,250–₹58,500</Badge></CardAction></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-3">{[['B0 · Raw reference',prototype.marketEvidence.baselines.B0.estimate,'84 exact-2BHK rows'],['B1 · Simple workflow',prototype.marketEvidence.baselines.B1.estimate,'9 effective rows'],['B2 · Trust layer',prototype.marketEvidence.baselines.B2.estimate,'8 effective rows under policy']].map(([label,value,detail], index) => <div key={label as string} className={`rounded-xl border p-4 ${index === 2 ? 'border-indigo-200 bg-indigo-50/50' : ''}`}><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1.5 text-2xl font-bold">{money(value as number)}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>)}</div><div className="mt-4 flex items-start gap-3 rounded-xl border border-sky-200 bg-sky-50 p-3.5 text-sm text-sky-950"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-sky-700" /><p>B2 moves only ₹250 from B1. Its proposed value is inspectability, reversible review and honest failure behavior; that incremental value is not yet proven.</p></div></CardContent></Card>
        <Card className="mt-4 border-amber-200 bg-amber-50/45"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert className="size-5 text-amber-800" />Decision-grade comparison: INSUFFICIENT</CardTitle><CardDescription>The system abstains because the evidence cannot resolve the maintenance basis or convert asking prices into achieved rents.</CardDescription><CardAction><Badge variant="outline" className="border-amber-300 text-amber-900">Failure state working as designed</Badge></CardAction></CardHeader><CardContent className="flex flex-col gap-3 text-sm sm:flex-row sm:items-center sm:justify-between"><p className="text-amber-950">Next action: obtain source-level maintenance evidence or retain this abstention.</p><Button variant="outline" render={<a href="#resolution-queue" aria-label="Open evidence resolution queue" />}>Open evidence request</Button></CardContent></Card>
        <Card id="listing-audit" className="mt-4 scroll-mt-28"><CardHeader><CardTitle>Comparable audit</CardTitle><CardDescription>All 86 supplied rows remain inspectable. Review-pending and collapsed rows have zero active weight.</CardDescription><CardAction><Badge variant="outline">{filtered.length} rows in view</Badge></CardAction></CardHeader><CardContent>
          <div className="mb-4 flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex flex-wrap gap-1.5">{([['material','Material · 12'],['all','All · 86'],['include','Included · 8'],['duplicate_collapsed','Collapsed · 2'],['needs_human_review','Review · 2'],['exclude','Excluded · 74']] as [Filter,string][]).map(([value,label]) => <Button key={value} size="sm" variant={filter === value ? 'default' : 'outline'} onClick={() => setActiveFilter(value)}>{label}</Button>)}</div><div className="relative w-full xl:w-72"><Search className="absolute left-2.5 top-2 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search ID, source, society, reason" className="pl-8" aria-label="Search listing audit" /></div></div>
          <div className="overflow-x-auto rounded-xl border"><Table><TableHeader><TableRow><TableHead>Listing</TableHead><TableHead>Source</TableHead><TableHead>Observed</TableHead><TableHead>Asking</TableHead><TableHead>B2 state</TableHead><TableHead>Weight</TableHead><TableHead>Observable basis</TableHead></TableRow></TableHeader><TableBody>{visibleRows.map((listing) => <TableRow key={listing.listingId} className="cursor-pointer" onClick={() => setSelected(listing)}><TableCell className="font-semibold">{listing.listingId}</TableCell><TableCell>{listing.observed.source}</TableCell><TableCell className="min-w-52"><span className="font-medium">{listing.observed.society}</span><span className="block text-xs text-muted-foreground">{listing.observed.bhk}BHK · {listing.observed.areaSqft ?? '—'} sq ft · {listing.observed.furnishing}</span></TableCell><TableCell className="font-medium">{money(listing.observed.rentInr)}</TableCell><TableCell><StateBadge state={listing.decision.b2State} /></TableCell><TableCell>{listing.decision.effectiveWeight}</TableCell><TableCell className="min-w-56 whitespace-normal text-xs text-muted-foreground">{listing.decision.reasonCodes.length ? listing.decision.reasonCodes.join(' · ').replaceAll('_',' ') : 'Meets candidate policy'}</TableCell></TableRow>)}{!visibleRows.length && <TableRow><TableCell colSpan={7} className="h-28 text-center text-muted-foreground">No rows match this filter.</TableCell></TableRow>}</TableBody></Table></div>
          <div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><p>Click a row to inspect facts, derivations, provenance and consequence.</p><div className="flex items-center gap-2"><Button size="icon-sm" variant="outline" aria-label="Previous page" disabled={safePage <= 1} onClick={() => setPage((value) => Math.max(1,value-1))}><ChevronLeft /></Button><span>Page {safePage} of {totalPages}</span><Button size="icon-sm" variant="outline" aria-label="Next page" disabled={safePage >= totalPages} onClick={() => setPage((value) => Math.min(totalPages,value+1))}><ChevronRight /></Button></div></div>
        </CardContent></Card>
        <Card className="mt-4"><CardHeader><CardTitle>Reversible review workspace</CardTitle><CardDescription>Precomputed counterfactuals show impact without overwriting the frozen result.</CardDescription><CardAction><Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-900">Local demonstration only · not saved</Badge></CardAction></CardHeader><CardContent><div className="grid gap-4 xl:grid-cols-[1fr_280px]"><div className="grid gap-2 sm:grid-cols-2">{prototype.marketEvidence.counterfactuals.map((item) => <button key={item.id} onClick={() => setWhatIfId(item.id)} className={`rounded-xl border p-3 text-left transition-colors ${whatIfId === item.id ? 'border-indigo-300 bg-indigo-50' : 'hover:bg-muted/50'}`}><span className="text-sm font-semibold">{item.listing_id}</span><span className="mt-1 block text-xs text-muted-foreground">{item.action.replaceAll('_',' ')}</span></button>)}</div><div className="rounded-xl border bg-muted/35 p-4"><p className="text-xs font-medium text-muted-foreground">Local scenario result</p><p className="mt-1.5 text-2xl font-bold">{whatIf ? money(whatIf.estimate) : money(prototype.marketEvidence.baselines.B2.estimate)}</p><p className="mt-1 text-xs text-muted-foreground">{whatIf ? `${whatIf.delta_from_baseline >= 0 ? '+' : ''}${money(whatIf.delta_from_baseline)} · ${whatIf.effective_count} effective rows` : 'Frozen B2 baseline · 8 effective rows'}</p><Button size="sm" variant="ghost" className="mt-3" disabled={!whatIfId} onClick={() => setWhatIfId(null)}><RotateCcw /> Reset baseline</Button></div></div></CardContent></Card>
        <Card id="economics-context" className="mt-4 scroll-mt-28 border-dashed"><CardHeader><CardTitle>Decision context from supplied assessment</CardTitle><CardDescription>Separate provenance: these economics do not numerically consume the ₹58,250 market estimate.</CardDescription><CardAction><Badge variant="outline">Reference only · not verified</Badge></CardAction></CardHeader><CardContent><Tabs value={scenarioId} onValueChange={setScenarioId}><div className="overflow-x-auto pb-2"><TabsList>{prototype.economics.scenarios.map((item) => <TabsTrigger key={item.id} value={item.id}>{item.label}</TabsTrigger>)}</TabsList></div>{prototype.economics.scenarios.map((item) => <TabsContent key={item.id} value={item.id} className="pt-3"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Occupancy-adjusted revenue</p><p className="mt-1 text-xl font-bold">{money(item.occupancyAdjustedRevenue)}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Monthly owner cost</p><p className="mt-1 text-xl font-bold">{money(item.monthlyOwnerCost)}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Capital employed</p><p className="mt-1 text-xl font-bold">{money(item.capitalEmployed)}</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs text-amber-900">Simple payback</p><p className="mt-1 text-xl font-bold text-amber-950">{item.simplePaybackMonths} months</p></div></div><div className="mt-3 rounded-xl border bg-muted/30 p-3 text-xs leading-5 text-muted-foreground"><p className="font-semibold text-foreground">{item.model}</p><p>{item.note}</p><p>Omits: {item.omissionCodes.join(', ').replaceAll('_',' ')}.</p></div></TabsContent>)}</Tabs>{scenario.id === 'room_2_downside_fixed_deposit' && <div className="mt-3 flex gap-2 rounded-xl border border-sky-200 bg-sky-50 p-3 text-xs leading-5 text-sky-950"><Info className="mt-0.5 size-4 shrink-0" /><p>The supplied 57.1-month case fixes tenant deposits at ₹1.80L. If deposits remain linked to 2.5× revenue, the candidate sensitivity is 58.8 months.</p></div>}</CardContent></Card>
        <Card id="resolution-queue" className="mt-4 scroll-mt-28"><CardHeader><CardTitle>Evidence resolution queue</CardTitle><CardDescription>Each request names the owner, required proof and consequence. Checking an item changes this browser view only.</CardDescription><CardAction><Badge variant="outline">{prototype.evidenceResolutionQueue.length-resolvedQueue.length} unresolved</Badge></CardAction></CardHeader><CardContent className="space-y-2">{prototype.evidenceResolutionQueue.map((item) => { const done = resolvedQueue.includes(item.id); return <button key={item.id} onClick={() => setResolvedQueue((items) => done ? items.filter((id) => id !== item.id) : [...items,item.id])} className={`flex w-full gap-3 rounded-xl border p-3 text-left transition-colors ${done ? 'bg-muted/45 opacity-65' : 'hover:bg-muted/30'}`}><span className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded border ${done ? 'border-primary bg-primary text-primary-foreground' : 'border-input bg-background'}`}>{done && <Check className="size-3.5" />}</span><span className="min-w-0"><span className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{item.issue}</span><Badge variant="outline">{item.owner}</Badge>{item.status === 'blocked' && <Badge variant="outline" className="border-amber-200 bg-amber-50 text-amber-900">Blocked</Badge>}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground"><strong className="text-foreground">Required:</strong> {item.requiredProof} <strong className="text-foreground">Consequence:</strong> {item.consequence}</span></span></button>; })}<p className="pt-2 text-xs text-muted-foreground">Demonstration state only. Nothing is assigned, sent, persisted or authorized.</p></CardContent></Card>
        <footer className="my-8 rounded-xl border bg-card p-4 text-xs text-muted-foreground"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><p><span className="font-semibold text-foreground">Policy</span><br />v{prototype.snapshot.policyVersion} · candidate proposal</p><p><span className="font-semibold text-foreground">Input hash</span><br /><code>{prototype.snapshot.inputHash}</code></p><p><span className="font-semibold text-foreground">Output hash</span><br /><code>{prototype.snapshot.outputHash}</code></p><p><span className="font-semibold text-foreground">Calculation hash</span><br /><code>{prototype.snapshot.calculationVersion}</code></p></div><p className="mt-3 border-t pt-3">Single-case demonstrator. Prefix aliases, duplicate rules and thresholds are candidate-authored, not validated Flent production policy. CP-0081 is a packet-grounded manual annotation.</p></footer>
      </div></section>
    </div>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-2xl">{selected && <><DialogHeader><DialogTitle>{selected.listingId} · evidence record</DialogTitle><DialogDescription>Observed facts remain separate from derived fields and policy decisions.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Observed</p><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-muted-foreground">Source label</dt><dd className="font-medium">{selected.observed.source}</dd></div><div><dt className="text-muted-foreground">Society text</dt><dd className="font-medium">{selected.observed.society}</dd></div><div><dt className="text-muted-foreground">Attributes</dt><dd className="font-medium">{selected.observed.bhk}BHK · {selected.observed.areaSqft ?? 'missing'} sq ft · {selected.observed.furnishing}</dd></div><div><dt className="text-muted-foreground">Asking / last seen</dt><dd className="font-medium">{money(selected.observed.rentInr)} · {selected.observed.lastSeenDate}</dd></div></dl></div><div className="rounded-xl border p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Derived / candidate policy</p><dl className="mt-3 space-y-2 text-sm"><div><dt className="text-muted-foreground">Normalized family</dt><dd className="font-medium">{selected.derived.societyFamily}</dd></div><div><dt className="text-muted-foreground">Age at cutoff</dt><dd className="font-medium">{selected.derived.lastSeenAgeDays} days</dd></div><div><dt className="text-muted-foreground">B2 state / weight</dt><dd className="mt-1 flex items-center gap-2"><StateBadge state={selected.decision.b2State} /><span>{selected.decision.effectiveWeight}</span></dd></div><div><dt className="text-muted-foreground">Reasons</dt><dd className="font-medium">{selected.decision.reasonCodes.length ? selected.decision.reasonCodes.join(', ').replaceAll('_',' ') : 'none'}</dd></div></dl></div></div>{selected.decision.duplicateGroup && <div className="rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm text-sky-950">Duplicate candidate group {selected.decision.duplicateGroup}; representative {selected.decision.representativeListingId}. This is an inference, not ground truth.</div>}{selected.decision.annotationType && <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">Manual annotation: {selected.decision.annotationType.replaceAll('_',' ')} · source {selected.decision.annotationSource}. It is not algorithmic detection.</div>}<DialogFooter showCloseButton /></>}</DialogContent></Dialog>
    <Dialog open={policyOpen} onOpenChange={setPolicyOpen}><DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Candidate comparison policy</DialogTitle><DialogDescription>Proposed for this exercise; not validated or approved as Flent production policy.</DialogDescription></DialogHeader><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">Area tolerance</p><p className="mt-1 text-lg font-bold">±{prototype.policy.comparability.area_tolerance_sqft} sq ft</p></div><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">Freshness</p><p className="mt-1 text-lg font-bold">≤{prototype.policy.comparability.max_last_seen_age_days} days</p></div><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">Society family</p><p className="mt-1 text-lg font-bold">Required</p></div></div><div><p className="mb-2 text-sm font-semibold">Sensitivity disclosure</p><Table><TableHeader><TableRow><TableHead>Area</TableHead><TableHead>Age</TableHead><TableHead>Rows</TableHead><TableHead>Median</TableHead></TableRow></TableHeader><TableBody>{prototype.marketEvidence.reasonable_policy_sensitivity.scenarios.map((item) => <TableRow key={`${item.area_tolerance_sqft}-${item.max_last_seen_age_days}`}><TableCell>±{item.area_tolerance_sqft}</TableCell><TableCell>{item.max_last_seen_age_days}d</TableCell><TableCell>{item.effective_count}</TableCell><TableCell>{money(item.estimate)}</TableCell></TableRow>)}</TableBody></Table></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-950">Hard gate: society-sharing permission can force PASS regardless of this estimate. This policy cannot resolve that risk.</div><DialogFooter showCloseButton /></DialogContent></Dialog>
    <Dialog open={runOpen} onOpenChange={setRunOpen}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>Frozen run details</DialogTitle><DialogDescription>Traceability for the evidence snapshot rendered on this page.</DialogDescription></DialogHeader><dl className="space-y-3 text-sm"><div><dt className="text-muted-foreground">Evidence cutoff</dt><dd className="font-medium">18 Aug 2026 · 17:00 IST</dd></div><div><dt className="text-muted-foreground">Scope</dt><dd className="font-medium">86 supplied listing rows · single Lakeview case</dd></div><div><dt className="text-muted-foreground">Policy authority</dt><dd className="font-medium">Candidate proposal · not production policy</dd></div><div><dt className="text-muted-foreground">Runtime behavior</dt><dd className="font-medium">Read-only proof snapshot; local interactions are not persisted</dd></div></dl><DialogFooter showCloseButton /></DialogContent></Dialog>
  </main>;
}
